[project]
authors = ["Aryan Rajoria <aryanrajoria1003@gmail.com>"]
channels = ["conda-forge"]
description = "Add a short description here"
name = "symbols-db"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
