"""Android triplet handling for vcpkg cross builds (I1).

All paths go through pathlib/tmp_path, so the tests make no
platform-specific assumptions about separators or drives.
"""

import pytest

from blint_db.utils.android import (
    ANDROID_TRIPLET_ABIS,
    android_triplet_abi,
    is_android_triplet,
    read_ndk_revision,
    read_triplet_api_level,
    triplet_target_os_arch,
)


@pytest.mark.parametrize(
    ("triplet", "abi"),
    [
        ("arm64-android", "arm64-v8a"),
        ("arm-android", "armeabi-v7a"),
        # Newer vcpkg renamed arm-android; both spellings are the same ABI.
        ("arm-neon-android", "armeabi-v7a"),
        ("x64-android", "x86_64"),
        ("x86-android", "x86"),
    ],
)
def test_android_triplets_map_to_the_four_abis(triplet, abi):
    assert ANDROID_TRIPLET_ABIS[triplet] == abi
    assert android_triplet_abi(triplet) == abi
    assert is_android_triplet(triplet)
    # The dynamic-linkage overlay triplets target the same ABI.
    assert android_triplet_abi(f"{triplet}-dynamic") == abi
    assert is_android_triplet(f"{triplet}-dynamic")


def test_host_triplets_are_not_android():
    assert not is_android_triplet("arm64-osx")
    assert not is_android_triplet("x64-linux")
    assert not is_android_triplet(None)
    assert android_triplet_abi("arm64-osx") is None


def test_triplet_target_os_arch_prefers_the_target_not_the_host():
    assert triplet_target_os_arch(
        "arm64-android-dynamic", host_os="osx", host_arch="arm64"
    ) == ("android", "arm64")
    assert triplet_target_os_arch(
        "arm-android", host_os="osx", host_arch="arm64"
    ) == ("android", "arm")
    assert triplet_target_os_arch(
        "x64-android", host_os="osx", host_arch="arm64"
    ) == ("android", "x64")
    assert triplet_target_os_arch(
        "x86-android", host_os="osx", host_arch="arm64"
    ) == ("android", "x86")
    # A host triplet keeps the host-derived pair the caller passed.
    assert triplet_target_os_arch(
        "arm64-osx", host_os="osx", host_arch="arm64"
    ) == ("osx", "arm64")
    assert triplet_target_os_arch(None, host_os="linux", host_arch="x64") == (
        "linux",
        "x64",
    )


def test_read_ndk_revision_parses_source_properties(tmp_path):
    ndk = tmp_path / "ndk"
    ndk.mkdir()
    (ndk / "source.properties").write_text(
        "### Auto-generated by prop.py\n"
        "Pkg.Desc = Android NDK\n"
        "Pkg.Revision = 28.2.13676358\n",
        encoding="utf-8",
    )
    assert read_ndk_revision(ndk) == "28.2.13676358"
    # Missing NDK location or unreadable source.properties: unknown, not
    # guessed.
    assert read_ndk_revision(None) is None
    assert read_ndk_revision(tmp_path / "does-not-exist") is None


def test_read_triplet_api_level_searches_overlay_then_builtin(tmp_path):
    vcpkg = tmp_path / "vcpkg"
    overlay = tmp_path / "overlay"
    (vcpkg / "triplets").mkdir(parents=True)
    (vcpkg / "triplets" / "community").mkdir(parents=True)
    overlay.mkdir()
    (vcpkg / "triplets" / "arm64-android.cmake").write_text(
        "set(VCPKG_TARGET_ARCHITECTURE arm64)\n"
        "set(VCPKG_CMAKE_SYSTEM_NAME Android)\n"
        "set(VCPKG_CMAKE_SYSTEM_VERSION 28)\n",
        encoding="utf-8",
    )
    (vcpkg / "triplets" / "community" / "arm-android.cmake").write_text(
        "set(VCPKG_TARGET_ARCHITECTURE arm)\n"
        "set(VCPKG_CMAKE_SYSTEM_NAME Android)\n"
        "set(VCPKG_CMAKE_SYSTEM_VERSION 24)\n",
        encoding="utf-8",
    )
    # The overlay wins over a same-named builtin.
    (overlay / "arm64-android-dynamic.cmake").write_text(
        "set(VCPKG_LIBRARY_LINKAGE dynamic)\n"
        "set(VCPKG_CMAKE_SYSTEM_VERSION 21)\n",
        encoding="utf-8",
    )
    assert read_triplet_api_level("arm64-android", vcpkg, None) == 28
    assert read_triplet_api_level("arm-android", vcpkg, None) == 24
    assert read_triplet_api_level("arm64-android-dynamic", vcpkg, overlay) == 21
    assert read_triplet_api_level("not-a-triplet", vcpkg, None) is None
    assert read_triplet_api_level("arm64-android", None, None) is None
