name: Build and Upload vcpkg blint-db mac

on:
  workflow_dispatch:
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: appthreat/blintdb

jobs:
  builder-darwin-arm64-vcpkg:
    runs-on: ['macos-hosted', 'arm64']
    timeout-minutes: 7200
    permissions:
      contents: write
      packages: write
    steps:
    - uses: actions/checkout@v4
    - name: Install uv
      uses: astral-sh/setup-uv@v5
    - name: Install dependencies
      run: |
        uv venv -p 3.12
        source .venv/bin/activate
        uv sync --all-extras --dev
        brew install --HEAD leleliu008/fpliu/ppkg
    - name: Clean up previous
      run: |
        rm -rf ${BLINT_DB_BOOTSTRAP_PATH}
    - name: Build and upload darwin arm64 db
      run: |
        mkdir -p ${BLINT_DB_BOOTSTRAP_PATH}
        source .venv/bin/activate
        uv run blint-db --clean-start -Z2
        python .oras/orasclient.py -p vcpkg-darwin-arm64
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GITHUB_USERNAME: ${{ github.actor }}
        BLINT_DB_BOOTSTRAP_PATH: ${{ runner.temp }}/blint-db-temp
        VCPKG_DISABLE_METRICS: true
