name: Build and Upload meson blint-db

on:
  workflow_dispatch:
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: appthreat/blintdb

jobs:
  builder-meson:
    runs-on: ['self-hosted', 'ubuntu', 'amd64']
    timeout-minutes: 7200
    if: false
    permissions:
      contents: write
      packages: write
    steps:
    - uses: actions/checkout@v4
    - name: Install uv
      uses: astral-sh/setup-uv@v5
    - name: Install dependencies
      run: |
        uv venv -p 3.12
        source .venv/bin/activate
        uv sync --all-extras --dev
    - name: Clean up previous
      run: |
        rm -rf ${BLINT_DB_BOOTSTRAP_PATH}
    - name: Build and upload db
      run: |
        mkdir -p ${BLINT_DB_BOOTSTRAP_PATH}
        source .venv/bin/activate
        uv run blint-db --clean-start -Z1
        python .oras/orasclient.py -p meson
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GITHUB_USERNAME: ${{ github.actor }}
        BLINT_DB_BOOTSTRAP_PATH: ${{ runner.temp }}/blint-db-temp

  builder-arm64-meson:
    runs-on: ['self-hosted', 'ubuntu', 'arm64']
    timeout-minutes: 7200
    permissions:
      contents: write
      packages: write
    steps:
    - uses: actions/checkout@v4
    - name: Install uv
      uses: astral-sh/setup-uv@v5
    - name: Install dependencies
      run: |
        uv venv -p 3.12
        source .venv/bin/activate
        uv sync --all-extras --dev
    - name: Clean up previous
      run: |
        rm -rf ${BLINT_DB_BOOTSTRAP_PATH}
    - name: Build and upload arm64 db
      run: |
        mkdir -p ${BLINT_DB_BOOTSTRAP_PATH}
        source .venv/bin/activate
        uv run blint-db --clean-start -Z1
        python .oras/orasclient.py -p meson-arm64
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GITHUB_USERNAME: ${{ github.actor }}
        BLINT_DB_BOOTSTRAP_PATH: ${{ runner.temp }}/blint-db-temp
