name: Build and Upload meson blint-db 0.1.0

on:
  schedule:
  - cron: "0 */6 * * *"
  workflow_dispatch:
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: appthreat/blintdb

jobs:
  builder:
    runs-on: dev1-actions2
    permissions:
      contents: write
      packages: write
    steps:
    - uses: actions/checkout@v4
      with:
        repository: AppThreat/blint-db
        path: blint-db
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install setuptools wheel twine build
        cd blint-db && python -m pip install .
    - name: Build and upload db
      run: |
        mkdir temp
        python blint-db/blint_db/cli.py -Z1
        echo $GITHUB_TOKEN | oras login ghcr.io -u $GITHUB_USERNAME --password-stdin
        cd blint-db
        oras push ghcr.io/appthreat/blintdb-vcpkg:v0.1 \
          --config ../.oras/config.json:application/vnd.oras.config.v1+json \
          --annotation-file ../.oras/annotations.json \
          ./blint.db:application/vnd.appthreat.vdb.layer.v1+tar \
        
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GITHUB_USERNAME: ${{ github.actor }}