name: Build and Upload vcpkg blint-db 0.1.0

on:
  schedule:
  - cron: "0 */12 * * *"
  workflow_dispatch:
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: appthreat/blintdb

jobs:
  builder-vcpkg:
    runs-on: ['self-hosted', 'ubuntu', 'arm64']
    permissions:
      contents: write
      packages: write
    steps:
    - uses: actions/checkout@v4
      with:
        repository: AppThreat/blint-db
        path: blint-db
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install setuptools wheel twine build
        cd blint-db && python -m pip install .
    - name: Clean up previous
      run: |
        cd blint-db
        rm -f info.log
        rm -f blint.db
    - name: Build and upload db
      run: |
        mkdir -p temp
        cd blint-db/
        python blint-db/blint_db/cli.py -Z2
        python ./.oras/orasclient.py
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GITHUB_USERNAME: ${{ github.actor }}
