name: Build and Upload vcpkg blint-db

on:
  workflow_dispatch:
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: appthreat/blintdb

jobs:
  builder-vcpkg:
    runs-on: ['self-hosted', 'ubuntu', 'amd64']
    timeout-minutes: 3600
    permissions:
      contents: write
      packages: write
    steps:
    - uses: actions/checkout@v4
    - name: Install uv
      uses: astral-sh/setup-uv@v5
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.13'
    - name: Install dependencies
      run: |
        uv venv -p 3.13
        source .venv/bin/activate
        uv sync --all-extras --dev
    - name: Clean up previous
      run: |
        rm -rf ${BLINT_DB_TEMP}
    - name: Build and upload db
      run: |
        mkdir -p ${BLINT_DB_TEMP}
        source .venv/bin/activate
        uv run blint-db --clean-start -Z2
        python .oras/orasclient.py -p vcpkg
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GITHUB_USERNAME: ${{ github.actor }}
        BLINT_DB_TEMP: ${{ runner.temp }}/blint-db-temp
        VCPKG_DISABLE_METRICS: true
